name: Update Major Version Tag

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract major version and update tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Latest tag is $TAG"
          MAJOR_VERSION=${TAG%%.*}
          echo "Major version is $MAJOR_VERSION"
          git tag -f $MAJOR_VERSION $TAG
          git push origin $MAJOR_VERSION --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
